### ISSUE TITLE
not the right rbf path

### ISSUE THREAD

**Issue by graschbaten** [RetroDriven/MiSTerArduboy#1]
please change the ARDUBOY_RBF_PATH="_Consoles" path to ARDUBOY_RBF_PATH="_Console"
because _Console is the path from mister update script

**Comment by RetroDriven** [comment]
Good catch. I'm sorry about that. I'll get this fixed in the Script and INI file ASAP.

Thanks for reporting this issue.

**Comment by RetroDriven** [comment]
This has been fixed within the Script and INI files. Thanks again for finding and reporting the typo.
