### ISSUE TITLE
missing a preceding '/' for .rbf path in ini and script

### ISSUE THREAD

**Issue by esmith13** [RetroDriven/MiSTerArduboy#2]
just a note that the arduboy updater puts the .rbf file directly on /media/fat and NOT in /media/fat/_Console like it should.

to fix myself I had to change this in the .ini file:
```
#Directoy to sav the Arduboy Core/RBF file to
ARDUBOY_RBF_PATH="_Console"

```
to:
```
#Directoy to sav the Arduboy Core/RBF file to
ARDUBOY_RBF_PATH="/_Console"

```
the same mistake is in the script itself as well. I assume it would need to be corrected there as well for a use case where the .ini file does not exist.

Thanks so much for all your hard work making the MiSTer community a better and more n00b-friendly place!!

**Comment by RetroDriven** [comment]
I just tested this without any changes and I didn't run into this same issue. Further down in the code there is `CORE_CATEGORY_PATHS["arcade-cores"]="$BASE_PATH/$ARDUBOY_RBF_PATH"` which would translate to` /media/fat/_Console` if everything is left untouched via the Script and/or INI File.

When you get a chance can you please try testing this again with a fresh and untouched INI file?

You're welcome - I'm glad you find what I'm doing helpful.

**Comment by RetroDriven** [comment]
The Official MiSTer Updater is now handling the Arduboy update process. The code for this has been removed on my end completely to avoid issues/duplicate RBF Core Files.
